initial_pheromone: 1.0
alpha: 1.0          # Pheromone importance
beta: 2.0           # Heuristic importance
evaporation_rate: 0.1
global_evaporation: 0.05
q: 100              # Pheromone constant
num_ants: 20
iterations: 100
min_pheromone: 0.01